### ISSUE TITLE
Inline object notation

### ISSUE THREAD

**Issue by 1ec5** [mapbox/expression-jamsession#25]
The readme says this library doesn’t have a way to represent JSON object literals for the `literal` expression, due to a `jsep` limitation. Perhaps there could be an inline notation such as `object(key1, value1, key2, value2, …)`.

There are a few error conditions to consider:

* Duplicate keys
* An odd number of arguments to the function
* Keys that aren’t strings

Besides `literal`, an object literal syntax is needed because mapbox/mapbox-gl-js#6270 introduced a `Collator` object type that can be passed into various comparison expressions.

/cc @dasulit @davidtheclark @samanpwbb @anandthakker @ChrisLoer

**Comment by anandthakker** [comment]
Looks like there's a PR adding object literal support: https://github.com/soney/jsep/pull/14

**Comment by 1ec5** [comment]
The `number-format` operator introduced in mapbox/mapbox-gl-js#7626 also takes an options object as an argument.

**Comment by samanpwbb** [comment]
I think it would make most sense for objects to be represented as token that, on click, expose a dedicated UI for adjusting object properties. Here's a complex and specific example:

![Screen Shot 2019-07-09 at 12 58 24 PM](https://user-images.githubusercontent.com/108094/60908184-437ba600-a249-11e9-8023-461f89e22c24.png)
