### ISSUE TITLE
Update operators list for mapbox-gl-js v0.45

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/expression-jamsession#26]
There are a bunch of new expressions in v0.45: 

Practical expressions: `abs`, `ceil`, `floor`, `length`, `round`.
Weird ones: `collator`, `resolved-locale`, `line-progress`, `is-supported-script`.

**Comment by samanpwbb** [comment]
I know we don't want to make mapbox-gl a dependency of expressions-jamsession, but I wonder if we should make mapbox-gl a dev-dependency so we can assert that all expressions are covered in https://github.com/mapbox/expression-jamsession/blob/master/src/expression-operators.js.

**Comment by davidtheclark** [comment]
@samanpwbb That file is automatically built from the style spec: https://github.com/mapbox/expression-jamsession/blob/master/scripts/build-operator-whitelist.js. So if you update the local version of the spec you should get an updated list. Does that cover your concern?
