### ISSUE TITLE
Is this library still maintained?

### ISSUE THREAD

**Issue by stevage** [mapbox/expression-jamsession#32]
Ah, the classic "future of the repo" issue. It looks like there is no development of any kind in nearly two years. Time to maybe officially abandon it?

**Comment by elifitch** [comment]
@stevage Yep, it is still maintained! Mapbox Studio uses jamsession to power the formula UI in fact. It's been doing a good job for us without many code changes or updates, so it hasn't received a ton of attention in the last while. I'm going to close this issue as "question answered" but please feel free to reopen if there are further questions or concerns 💖
