### ISSUE TITLE
Add support for index-of, slice, distance, and within expressions

### ISSUE THREAD

**Issue by elifitch** [mapbox/expression-jamsession#34]
There are new expressions introduced since GL 1.9 that need support in expression jamsession. 

https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/#index-of
https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/#slice
https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/#distance
https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/#within

**Comment by maciekglowacki** [comment]
I'll try to implement support for these features :D
